image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    
before_script:
  - rm -rf .terraform
  - terraform --version
  - terraform init aws
  
stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate aws

plan:
  stage: plan
  script:
    - terraform plan aws -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply aws -input=false "planfile"
  dependencies:
    - plan
  when: manual