variables:
  GIT_SUBMODULE_STRATEGY: recursive
  AWS_DEFAULT_REGION: eu-central-1 
  BUCKET_NAME: maartens.website
  CLOUDFRONT_DISTRIBUTION: E2ZELB92G50031

stages:
  - build
  - deploy

build:
  stage: build
  image: monachus/hugo
  script:
    - hugo -s site -d ../public
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: deploy
  image: "python:latest"
  dependencies:
    - build
  before_script:
    - pip install awscli
    - aws s3 rm s3://${BUCKET_NAME}/ --recursive # cleanup before continuing
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION} --paths "/*" #clear cloudfront cache
  script:
    - aws s3 cp public s3://${BUCKET_NAME}/ --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/
