baseUrl = "https://maartens.website"
languageCode = "en-us"
title = "Maartens website"
canonifyURLs = true
enableRobotsTXT = true
relativeURLs = true

[params]
    description = "Maarten de Klerk's personal website"